# Generated by Django 5.2.12 on 2026-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journalentry",
            old_name="chased",
            new_name="above_8_20_50",
        ),
        migrations.RenameField(
            model_name="journalentry",
            old_name="countertrend",
            new_name="ema_confluence",
        ),
        migrations.RenameField(
            model_name="journalentry",
            old_name="revenge_trade",
            new_name="sma_confluence",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="discipline",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="fear",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="asia_high",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="asia_low",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="globex_high",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="globex_low",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="key_resistance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="key_support",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="london_high",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="london_low",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="stop_loss_placed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="trend_aligned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="vwap_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="bias",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
