# Generated by Django 5.2.12 on 2026-03-08 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_rename_chased_journalentry_above_8_20_50_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("user", "date")},
        ),
        migrations.RemoveField(
            model_name="screenshot",
            name="journal",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="a_plus_setup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="dominant_emotion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="emotion_confidence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="emotion_discipline",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="emotion_fear",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="emotion_focus",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="followed_plan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="how_day_turned_out",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="htf_bias_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="improvement_tomorrow",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mistake_broke_time_rules",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mistake_chased",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mistake_countertrend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mistake_revenge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mistake_skipped_aplus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mistake_traded_news",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="session_bias",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bullish", "Bullish"),
                    ("bearish", "Bearish"),
                    ("range", "Range"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tf_15m",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tf_1m",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tf_30m",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tf_4h",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tf_60m",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screenshot",
            name="caption",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="screenshot",
            name="trade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screenshots",
                to="journal.trade",
            ),
        ),
        migrations.AddField(
            model_name="screenshot",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="displacement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="emotion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trade",
            name="entry_fill_50",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="fresh_ifvg",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="htf_confirmation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="is_a_plus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="is_auto_liq",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="result",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="trade",
            name="stop_points",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="target_points",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="date",
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="bias",
        ),
    ]
