# Generated by Django 5.2.12 on 2026-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_alter_journalentry_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="emotion_after",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="emotion_before",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="followed_risk_rules",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="instruments_traded",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mistakes_made",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="session_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("asia", "Asia"),
                    ("london", "London"),
                    ("new_york", "New York"),
                    ("midday", "Midday"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="stopped_at_max_loss",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="trade_quality_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A – Perfect discipline"),
                    ("B", "B – Minor mistakes"),
                    ("C", "C – Emotional trading"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="what_did_well",
            field=models.TextField(blank=True),
        ),
    ]
