# Generated by Django 5.2.12 on 2026-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_journalentry_emotion_after_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="risk_per_trade",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="strategy_setup",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ifvg", "IFVG"),
                    ("fvg", "FVG"),
                    ("ob", "Order Block"),
                    ("bos", "Break of Structure"),
                    ("liquidity", "Liquidity Sweep"),
                    ("vwap", "VWAP Reclaim"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="time_of_day_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open (9:30–10:00)"),
                    ("mid_morning", "Mid-Morning (10:00–11:30)"),
                    ("lunch", "Lunch (11:30–13:00)"),
                    ("afternoon", "Afternoon (13:00–15:30)"),
                    ("close", "Close (15:30–16:00)"),
                ],
                max_length=20,
            ),
        ),
    ]
