# Generated by Django 5.2.12 on 2026-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0006_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="assigned_clients",
        ),
        migrations.AddField(
            model_name="trade",
            name="ignition_move",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_grade",
            field=models.CharField(
                blank=True,
                choices=[("A+", "A+"), ("A", "A"), ("B", "B"), ("C", "C"), ("F", "F")],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="tradingaccount",
            name="account_balance",
            field=models.FloatField(default=50000.0),
        ),
        migrations.AlterField(
            model_name="trade",
            name="strategy_setup",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ignition", "Ignition"),
                    ("vwap_rejection", "VWAP Rejection"),
                    ("momentum_continuation", "Momentum Continuation"),
                    ("opening_drive", "Opening Drive"),
                    ("liquidity_sweep", "Liquidity Sweep"),
                    ("ifvg", "IFVG"),
                    ("fvg", "FVG"),
                    ("ob", "Order Block"),
                    ("bos", "Break of Structure"),
                    ("vwap", "VWAP Reclaim"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
