# Generated by Django 5.2.12 on 2026-03-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0007_remove_userprofile_assigned_clients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("client", "Client"),
                    ("assistant", "Assistant"),
                ],
                default="client",
                max_length=10,
            ),
        ),
    ]
