# Generated by Django 5.2.12 on 2026-04-01 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_tradingaccount_owner_tradingaccount_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('evaluation', 'Evaluation'), ('funded', 'Funded'), ('blown', 'Blown')], default='active', max_length=20),
        ),
    ]
