# Generated by Django 5.2.12 on 2026-04-02 14:28

import django.db.models.deletion
from collections import defaultdict

from django.conf import settings
from django.db import migrations, models


def dedupe_trading_account_names(apps, schema_editor):
    TradingAccount = apps.get_model("journal", "TradingAccount")
    buckets = defaultdict(list)
    for row in TradingAccount.objects.filter(deleted_at__isnull=True):
        if row.owner_id is None:
            continue
        buckets[(row.owner_id, row.name)].append(row)
    for (owner_id, _name), rows in buckets.items():
        if len(rows) <= 1:
            continue
        used = {
            r.name
            for r in TradingAccount.objects.filter(
                owner_id=owner_id, deleted_at__isnull=True
            )
        }
        base = rows[0].name
        for ta in rows[1:]:
            n = 2
            candidate = f"{base} ({n})"
            while candidate in used:
                n += 1
                candidate = f"{base} ({n})"
            used.add(candidate)
            ta.name = candidate
            ta.save(update_fields=["name"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_trading_account_status_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_import_trading_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_default_import', to='journal.tradingaccount'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_import_trading_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_last_import', to='journal.tradingaccount'),
        ),
        migrations.RunPython(dedupe_trading_account_names, noop),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True),
                fields=('owner', 'name'),
                name='journal_tradingaccount_owner_name_alive_uniq',
            ),
        ),
    ]
